# Generated by Django 4.1 on 2022-08-22 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0005_my_business_delete_business_delete_offer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Updates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('text', models.CharField(max_length=255)),
                ('date_posted', models.DateTimeField(verbose_name='Date Posted')),
                ('posted_by', models.CharField(max_length=30)),
            ],
        ),
    ]
