# Generated by Django 4.1 on 2022-08-22 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0006_updates'),
    ]

    operations = [
        migrations.CreateModel(
            name='My_updates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('text', models.CharField(max_length=255)),
                ('my_date', models.CharField(max_length=20)),
                ('posted_by', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='Updates',
        ),
    ]
